server:
  port: 8001

spring:
  application:
    name: cloud-payment-service
  datasource:
    db3:
      type: com.alibaba.druid.pool.DruidDataSource
      username: root
      password: gxs:666
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://127.0.0.1:3306/db2019?useUnicode=true&characterEncoding=UTF-8&useSSL=true&serverTimezone=UTC

    db1:
      jdbc-url: jdbc:mysql://127.0.0.1:3306/cloud_1?useUnicode=true&characterEncoding=UTF-8&useSSL=true&serverTimezone=UTC
      username: root
      password: gxs:666
      driver-class-name: com.mysql.cj.jdbc.Driver

#    db2:
#      jdbc-url: jdbc:mysql://127.0.0.1:3306/db2019?useUnicode=true&characterEncoding=UTF-8&useSSL=true&serverTimezone=UTC
#      username: root
#      password: gxs:666
#      driver-class-name: com.mysql.cj.jdbc.Driver

  devtools:
    remote:
      restart:
        enabled: true

#mybatis:
#  mapperLocations: classpath:mapper/*.xml
#  type-aliases-package: com.atguigu.springcloud.entities
#eureka:
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      defaultZone: http://eureka7001.com:7001/eureka #,http://eureka7002.com:7002/eureka #配置注册中心集群
#  #      defaultZone: http://guixiansongstudio.xyz:7001/eureka,http://guixiansongstudio.xyz:7002/eureka
#  instance:
#    instance-id: payment8001  #服务器名称修改
#    prefer-ip-address: true  #服务器ip地址提示
#    lease-renewal-interval-in-seconds: 1 #Eureka客户端向服务端发送心跳的时间间隔，单位为秒（默认是30秒）
#    lease-expiration-duration-in-seconds: 2 #Eureka服务端在收到最后一次心跳后等待时间上限，单位为秒（默认为90秒），超时将剔除服务