server:
#  port: 8004
  port: 8080
spring:
  application:
    name: cloud-provider-payment8004
  cloud:
    zookeeper:
#      connect-string: 172.17.0.2:2181
      block-until-connected-wait: 15000
      connect-string: 127.0.0.1:2181
